.read sql/log_table.sql
.read sql/company_table.sql
.read sql/paydb_table.sql
.read sql/statement_tables.sql
.read sql/upload_table.sql
.read sql/otp_table.sql
.read sql/log_table.sql
.read sql/smslog_table.sql
.read sql/staff_table.sql
.read sql/paysmslog_table.sql